name: Build Elite Dictionary APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Flet and Build
        run: |
          pip install flet
          # Используем main.py, так как он в твоем репозитории
          flet build apk main.py --product "EliteDictionary"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: elite-dictionary-apk
          path: build/apk/app-release.apk
